version: "3.9"
services:
  web:
    build: .
    ports:
      - 8080:8080
    links:
      - "db:db"
    logging:
      driver: "json-file"
    depends_on:
      - db
    restart: on-failure
    environment:
      MYSQL_HOST_IP: db
  db:
    container_name: db
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'score'
      MYSQL_PASSWORD: 'hireme'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    expose:
      - '3306'